defaults: &defaults
    working_directory: ~/feedbackfruits-knowledge-tudelft-library-miner
    docker:
      - image: node:10
        environment:
          NODE_ENV: test
          OUTPUT_TOPIC: test_update_requests
          KAFKA_ADDRESS: localhost:9092
          START_PAGE: 1
          END_PAGE: 2
          PAGE_SIZE: 10
      - image: wurstmeister/zookeeper:latest
      - image: wurstmeister/kafka:1.0.0
        environment:
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_CREATE_TOPICS: "test_updates:1:1,test_update_requests:1:1"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run: yarn test
      - run: yarn run coverage

      - store_artifacts:
          path: coverage
  deploy-branch:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Prepare deployment
          command: |
            # Setup Heroku CLI
            bash .circleci/setup-heroku.sh

            # Run credentials script as default user
            bash .circleci/setup-heroku-credentials.sh
      - deploy:
          name: Deploy to Heroku
          command: |
            heroku config:add GIT_TAG=`git describe --tags --always` --app staging-fbf-know-tud-lib-miner
            git push git@heroku.com:staging-fbf-know-tud-lib-miner.git $CIRCLE_SHA1:refs/heads/master -f
            heroku ps:scale web=0 -a staging-fbf-know-tud-lib-miner
            heroku run:detached yarn start -a staging-fbf-know-tud-lib-miner
  deploy-tag:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Prepare deployment
          command: |
            # Setup Heroku CLI
            bash .circleci/setup-heroku.sh

            # Run credentials script as default user
            bash .circleci/setup-heroku-credentials.sh
      - deploy:
          name: Deploy to Heroku
          command: |
            heroku config:add GIT_TAG=`git describe --tags --always` --app fbf-knowledge-tud-lib-miner
            git push git@heroku.com:fbf-knowledge-tud-lib-miner.git $CIRCLE_SHA1:refs/heads/master -f
            heroku ps:scale web=0 -a fbf-knowledge-tud-lib-miner
            heroku run:detached yarn start -a fbf-knowledge-tud-lib-miner

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy-branch:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - deploy-tag:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
